spring:
  datasource:
    url: jdbc:mysql://mysql8:3306/dataease10?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "#Admin168"
  flyway:
    url: jdbc:mysql://mysql8:3306/dataease10?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    user: root
    password: "#Admin168"
  data:
    redis:
      host: redis-dataease
      port: 6379
      password:
      database: 0

mybatis-plus:
  mapper-locations: classpath:mybatis/*.xml

